### ISSUE TITLE
Something seems to have broken cmdQUIT

### ISSUE THREAD

**Issue by Heufneutje** [ElementalAlchemist/txircd#111]
```
2015-04-19 11:07:12+0200 [IRCUser,0,::ffff:127.0.0.1] Unhandled Error
        Traceback (most recent call last):
          File "/home/stefan/Development/Python/txircd/env/local/lib/python2.7/site-packages/twisted/python/log.py", line 88, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/home/stefan/Development/Python/txircd/env/local/lib/python2.7/site-packages/twisted/python/log.py", line 73, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/home/stefan/Development/Python/txircd/env/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/home/stefan/Development/Python/txircd/env/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/home/stefan/Development/Python/txircd/env/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
            why = selectable.doRead()
          File "/home/stefan/Development/Python/txircd/env/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 209, in doRead
            return self._dataReceived(data)
          File "/home/stefan/Development/Python/txircd/env/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 215, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/home/stefan/Development/Python/txircd/txircd/user.py", line 87, in dataReceived
            self.disconnect("Invalid data")
          File "/home/stefan/Development/Python/txircd/txircd/user.py", line 211, in disconnect
            self.ircd.runActionProcessing("quitmessage", userSendList, self, reason, users=[self] + userSendList)
          File "/home/stefan/Development/Python/txircd/txircd/ircd.py", line 619, in runActionProcessing
            action[0](data, *params, **kw)
        exceptions.TypeError: sendQuitMessage() got an unexpected keyword argument 'users'
```

**Comment by ElementalAlchemist** [comment]
Fixed in cb431053ab98302441a54e87cb079fee112ae4c1.
